export const typeAmtOP = [
    { label: 'Sin factuacion electronica', value: 1 },
    { label: 'Pruebas', value: 2 },
    { label: 'Producción', value: 3 },
]

export const typeDocsOP = [
    { id: 1, label: 'Ajuste tomado de inventario', value: 'Ajuste tomado de inventario' },
    { id: 2, label: 'Factura', value: 'Factura' },
    { id: 3, label: 'Nota de credito', value: 'Nota de credito' },
    { id: 4, label: 'Ticket', value: 'Ticket' },
    { id: 5, label: 'Compras', value: 'Compras' },
    { id: 6, label: 'Ingreso Mercaderia', value: 'Ingreso Mercaderia' },
    { id: 7, label: 'Egreso de Mercaderia', value: 'Egreso de Mercaderia' },
    { id: 8, label: 'Nota de Credito', value: 'nota_credito' },
    { id: 9, label: 'Nota de Debito', value: 'nota_debito' },
    { id: 10, label: 'Mercaderia Provisional', value: 'mercaderia_provisional' },
    { id: 11, label: 'Produccion', value: 'produccion' },
    { id: 12, label: 'Guia de Remision', value: 'guia_remision' },
    { id: 13, label: 'Cheque', value: 'cheque' },
    { id: 14, label: 'Proformas', value: 'proformas' },
    { id: 15, label: 'Cierre Caja', value: 'cierre_caja' },
]

export const enlacesOp = [
    { id: 1, label: 'Factura 001-002', value: 'Factura 001-002' },
    { id: 2, label: 'retencion x factura', value: 'retencion x factura' },
    { id: 3, label: 'Compras', value: 'Compras' },
    { id: 4, label: 'Ajuste tomado de inventario', value: 'Ajuste tomado de inventario' },
    { id: 5, label: 'produccion', value: 'produccion' },
    { id: 6, label: 'Inventario Provisional', value: 'Inventario Provisional' },
    { id: 7, label: 'Ingreso Mercaderia', value: 'Ingreso Mercaderia' },
    { id: 8, label: 'Egreso de Mercaderia', value: 'Egreso de Mercaderia' },
    { id: 9, label: 'Nota de Credito', value: 'nota_credito' },
    { id: 10, label: 'Guia de Remision', value: 'guia_remision' },
    { id: 11, label: 'proforma', value: 'proforma' },
    { id: 12, label: 'Cierre Caja', value: 'cierre_caja' },
    { id: 13, label: 'cheque produbanco', value: 'cheque produbanco' },
    { id: 14, label: 'cheque pichincha', value: 'cheque pichincha' },
    { id: 15, label: 'no tributario', value: 'no tributario' },
    { id: 16, label: 'prod se', value: 'prod se' },
    { id: 17, label: 'gasto personal', value: 'gasto personal' },
    { id: 18, label: 'prod it', value: 'prod it' },
    { id: 19, label: 'mermas', value: 'mermas' },
    { id: 20, label: 'trans +', value: 'trasn' },
    { id: 21, label: 'consumo gerencia', value: 'consumo gerencia' },
    { id: 22, label: 'transferencia -', value: 'transferencia -' },
    { id: 23, label: 'requisicion', value: 'requisicion' },
    { id: 24, label: 'desechos', value: 'desechos' },
    { id: 25, label: 'consumo personal', value: 'consumo personal' },
    { id: 26, label: 'Factura 001-002', value: 'Factura 001-002' },
    { id: 27, label: 'retencion bancos tarjetas', value: 'retencion bancos tarjetas' },
]
export const documentos = [
    { id: 1, label: 'Factura 001-002', value: 'Factura 001-002' },
    { id: 2, label: 'retencion x factura', value: 'retencion x factura' },
    { id: 3, label: 'Compras', value: 'Compras' },
    { id: 4, label: 'Ajuste tomado de inventario', value: 'Ajuste tomado de inventario' },
    { id: 5, label: 'produccion', value: 'produccion' },
    { id: 6, label: 'Inventario Provisional', value: 'Inventario Provisional' },
    { id: 7, label: 'Ingreso Mercaderia', value: 'Ingreso Mercaderia' },
    { id: 8, label: 'Egreso de Mercaderia', value: 'Egreso de Mercaderia' },
    { id: 9, label: 'Nota de Credito', value: 'nota_credito' },
    { id: 10, label: 'Guia de Remision', value: 'guia_remision' },
    { id: 11, label: 'proforma', value: 'proforma' },
    { id: 12, label: 'Cierre Caja', value: 'cierre_caja' },
    { id: 13, label: 'cheque produbanco', value: 'cheque produbanco' },
    { id: 14, label: 'cheque pichincha', value: 'cheque pichincha' },
    { id: 15, label: 'no tributario', value: 'no tributario' },
    { id: 16, label: 'prod se', value: 'prod se' },
    { id: 17, label: 'gasto personal', value: 'gasto personal' },
    { id: 18, label: 'prod it', value: 'prod it' },
    { id: 19, label: 'mermas', value: 'mermas' },
    { id: 20, label: 'trans +', value: 'trasn' },
    { id: 21, label: 'consumo gerencia', value: 'consumo gerencia' },
    { id: 22, label: 'transferencia -', value: 'transferencia -' },
    { id: 23, label: 'requisicion', value: 'requisicion' },
    { id: 24, label: 'desechos', value: 'desechos' },
    { id: 25, label: 'consumo personal', value: 'consumo personal' },
    { id: 26, label: 'Factura 001-002', value: 'Factura 001-002' },
    { id: 27, label: 'retencion bancos tarjetas', value: 'retencion bancos tarjetas' },
]